#!/bin/bash

# write version
TO=20190427

# version check
CUR_VER=`cat /linux.txt | cut -c 24-31`

# change log
echo -e "\n20190426 to $TO update\n1. shutdown,halt command fix.\n"

read -p "[alert] apply update for $CUR_VER? (y / ctrl+c for exit.) : " INPUT
case $INPUT in
  y)
    # write update scipt
    echo "adb disconnect > /dev/null 2>&1" > /sbin/shutdown
    echo "adb shell shutdown > /dev/null 2>&1" >> /sbin/shutdown      

    # info message
    echo "[update] update to $TO finished..."
    
    # version management
    echo "ro.build.version.linux=$TO.120000" > /linux.txt
    
    ;;
  *)
    ;;
esac
