#!/bin/bash

# write version
TO=20190426

# version check
CUR_VER=`cat /linux.txt | cut -c 24-31`

# change log
echo -e "\n20190425 to $TO update\n1. /mnt/sdcard bind fix.\n2. vendor-rw execution permission error fix.\n"

read -p "[alert] apply update for $CUR_VER? (y / ctrl+c for exit.) : " INPUT
case $INPUT in
  y)
    # write update scipt
    sed -i -e "s/ATV 7/ATV/g" /usr/bin/version
    mkdir /storage
    chmod a+x /sbin/vendor-rw
    vendor-rw
    cat <<'EOF' > /vendor/etc/init.ghost.linux
# internal linux init script
ROOT=/data/linux
busybox sysctl -w net.ipv4.ip_forward=1
busybox rm -rf $ROOT/dev/*
busybox mount -t sysfs sysfs $ROOT/sys
busybox mount -t proc proc $ROOT/proc
busybox mount -o bind /dev $ROOT/dev
busybox mount -t devpts devpts $ROOT/dev/pts
busybox mkdir $ROOT/dev/shm
busybox mount -t tmpfs tmpfs $ROOT/dev/shm
busybox rm -rf $ROOT/run/*
busybox mount -t tmpfs tmpfs $ROOT/run
busybox mkdir $ROOT/run/lock
busybox mount -o bind /dev/socket $ROOT/dev/socket
mount -o bind,rshared /mnt $ROOT/mnt
busybox mount -o bind /system $ROOT/system
busybox mount -o bind /data $ROOT/data
busybox mkdir $ROOT/vendor
busybox mount -o bind /vendor $ROOT/vendor
busybox mount -o bind /storage $ROOT/storage
busybox chroot $ROOT /bin/su root -c "/etc/init.d/rc 3" > /dev/kmsg
EOF

    cat <<'EOF' > /etc/init.d/aolconfig
#!/bin/sh
### BEGIN INIT INFO
# Provides:          aolconfig
# Required-Start:    hostname $local_fs
# Required-Stop:     
# Default-Start:     1 2 3 4 5
# Default-Stop:      
# Short-Description: androidoverlinux config script
# Description:       config by djjproject
### END INIT INFO
do_start() {
    # AOL INIT SCRIPT
    rm /var/lib/plexmediaserver/Plex\ Media\ Server/plexmediaserver.pid
    mkdir /dev/net
    ln -s /dev/tun /dev/net/tun
    ln -s /dev/block/* /dev
    # disk uuid mount
    lsblk -o KNAME -r | grep 'sd[a-z][0-9]' > /dev/uuidmount
    cat /dev/uuidmount | while read block
    do
	echo "BLOCK is $block"
	uuid=`blkid -s UUID -o value '/dev/'$block`
	mkdir -p '/mnt/by-uuid/'$uuid
	mount -o bind '/mnt/media_rw/'$block '/mnt/by-uuid/'$uuid
    done
    lsblk -o KNAME | grep 'mmcblk1p' > /dev/uuidmount
    cat /dev/uuidmount | while read block
    do
        echo "BLOCK is $block"
	mkdir -p '/mnt/by-uuid/'$block
        mount -o bind '/mnt/media_rw/'$block '/mnt/by-uuid/'$block
    done
}
case "$1" in
  start)
    do_start
  ;;
  stop)
  ;;
  restart)
  ;;
  *)
    echo "Usage: "$1" {start|stop|restart}"
    exit 1
  ;;
esac
exit 0
EOF
    
    # info message
    echo "[update] update to $TO finished..."
    echo "[update] you should reboot device."
    
    # version management
    echo "ro.build.version.linux=$TO.120000" > /linux.txt
    
    ;;
  *)
    ;;
esac
