#!/bin/bash

# write version
TO=20190426

# version check
CUR_VER=`cat /linux.txt | cut -c 24-31`

# change log
echo -e "\n20190425 to $TO update (only for ATV8)\n1. /mnt/sdcard bind fix.\n2. vendor-rw execution permission error fix.\n"

read -p "[alert] apply update for $CUR_VER? (y / ctrl+c for exit.) : " INPUT
case $INPUT in
  y)
    # write update scipt
    sed -i -e "s/ATV 7/ATV 8/g" /usr/bin/version
    mkdir /storage
    chmod a+x /sbin/vendor-rw
    vendor-rw
    cat <<'EOF' > /vendor/etc/init.ghost.linux
# internal linux init script
ROOT=/data/linux
busybox sysctl -w net.ipv4.ip_forward=1
busybox rm -rf $ROOT/dev/*
busybox mount -t sysfs sysfs $ROOT/sys
busybox mount -t proc proc $ROOT/proc
busybox mount -o bind /dev $ROOT/dev
busybox mount -t devpts devpts $ROOT/dev/pts
busybox mkdir $ROOT/dev/shm
busybox mount -t tmpfs tmpfs $ROOT/dev/shm
busybox rm -rf $ROOT/run/*
busybox mount -t tmpfs tmpfs $ROOT/run
busybox mkdir $ROOT/run/lock
busybox mount -o bind /dev/socket $ROOT/dev/socket
mount -o bind,rshared /mnt $ROOT/mnt
busybox mount -o bind /system $ROOT/system
busybox mount -o bind /data $ROOT/data
busybox mkdir $ROOT/vendor
busybox mount -o bind /vendor $ROOT/vendor
busybox mount -o bind /storage $ROOT/storage
busybox chroot $ROOT /bin/su root -c "/etc/init.d/rc 3" > /dev/kmsg
EOF
    
    # info message
    echo "[update] update to $TO finished..."
    echo "[update] you should reboot device."
    
    # version management
    echo "ro.build.version.linux=$TO.120000" > /linux.txt
    
    ;;
  *)
    ;;
esac
