#!/bin/bash

# write version
TO=20190426

# version check
CUR_VER=`cat /linux.txt | cut -c 24-31`

# change log
echo -e "\n20190425 to $TO update\n1. /mnt/sdcard bind fix.\n2. vendor-rw execution permission error fix.\n"

read -p "[alert] apply update for $CUR_VER? (y / ctrl+c for exit.) : " INPUT
case $INPUT in
  y)
    # write update scipt
    mkdir /storage
    chmod a+x /sbin/vendor-rw
    vendor-rw
    echo "busybox mount -o bind /storage $ROOT/storage" >> /vendor/etc/init.ghost.linux
    
    # info message
    echo "[update] update to $TO finished..."
    echo "[update] you should reboot device."
    
    # version management
    echo "ro.build.version.linux=$TO.120000" > /linux.txt
    
    ;;
  *)
    ;;
esac
